this commit adds the ability to check for commits by article id
rorybush/news-api pull request #8
Opened 2022-12-14 12:16 UTC by rorybush

2022-12-14 12:39 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +        expect(comments).toBeInstanceOf(Array);
line 124 is not needed because if it's passing in a forEach loop bellow and has length of 11 then it's already covered that it must be an array - you could save a line of code here

2022-12-14 12:39 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +        console.log(res.body);
don't forget to take out old console.logs

2022-12-14 12:42 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +
missing one test here that if you run this endpoint on an article that has `no comments` - it should return a `200` and give back an empty array, in this instance it's still a happy path to receive no comments as long as the `article_id` is valid

2022-12-14 12:44 UTC, Pipe-Smoking-Rabbit commented on models/news-model.js
> +      return Promise.reject({ status: 404, msg: "No Article Found." });
this `if (result.rowCount === 0)` will give you a false negative when you include a test for an `article_id` that has no comments - a way around this is to call your `selectArticleById` model function in you controller as well! Because the model function `selectArticleById` is already written to throw an error when it can't find any matching articles

2022-12-14 12:46 UTC, Pipe-Smoking-Rabbit requested changes
Very good code! However importantly it needs one more test for when you use an `article_id` that has `0` comments it should return `200` and an empty array - if you need any guidance on how to do this still then don't be shy to put in an nchelp in the morning

2022-12-15 10:37 UTC, robert112233 approved these changes
Merge good work 👍

2022-12-15 10:37 UTC, robert112233 commented on controllers/news-controller.js
> +  ])
This is a great way to differentiate between invalid article and valid article but with no comments, well done 👍

2022-12-15 10:39 UTC, merged